# Generated by Django 2.1.7 on 2019-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('website', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('latitude', models.CharField(blank=True, max_length=16)),
                ('longitude', models.CharField(blank=True, max_length=16)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
