# Generated by Django 2.1.7 on 2019-04-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='business',
            table='Business',
        ),
    ]
