# Generated by Django 2.1.7 on 2019-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190422_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'ContactNumber',
            },
        ),
    ]
