# Generated by Django 2.1.7 on 2019-04-22 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owns_Contact_Number',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.ContactNumber')),
            ],
            options={
                'db_table': 'Owns_Contact_Number',
            },
        ),
    ]
