# Generated by Django 2.1.7 on 2019-04-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Has_Business_Info',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business')),
            ],
            options={
                'db_table': 'Has_Business_Info',
            },
        ),
        migrations.AlterModelTable(
            name='businessinfo',
            table='Business_Info',
        ),
        migrations.AlterModelTable(
            name='contactnumber',
            table='Contact_Number',
        ),
        migrations.AddField(
            model_name='has_business_info',
            name='info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessInfo'),
        ),
    ]
