# Generated by Django 2.1.7 on 2019-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20190422_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('from_time', models.CharField(max_length=8)),
                ('till_time', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Interval',
            },
        ),
    ]
