# Generated by Django 2.1.7 on 2019-04-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasOpeningHour',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Day')),
                ('opening_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Interval')),
            ],
            options={
                'db_table': 'Has_Opening_Hour',
            },
        ),
    ]
