# Generated by Django 2.1.7 on 2019-04-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_hasopeninghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRelated',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.Business')),
            ],
            options={
                'db_table': 'Food_Related',
            },
        ),
    ]
