# Generated by Django 2.1.7 on 2019-04-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20190422_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrelated',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.Business'),
        ),
    ]
