# Generated by Django 2.1.7 on 2019-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20190422_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'Menu_Item',
            },
        ),
    ]
