# Generated by Django 2.1.7 on 2019-04-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHasItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.MenuItem')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Menu')),
            ],
            options={
                'db_table': 'Menu_Hash_Item',
            },
        ),
    ]
