# Generated by Django 2.1.7 on 2019-04-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.FoodRelated')),
            ],
            options={
                'db_table': 'Coffee_Shop',
            },
        ),
    ]
