# Generated by Django 2.1.7 on 2019-04-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_reservable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.Business')),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
    ]
