# Generated by Django 2.1.7 on 2019-04-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservableItem',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.Business')),
                ('name', models.CharField(max_length=16)),
                ('from_time', models.CharField(max_length=8)),
                ('till_time', models.CharField(max_length=8)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Reservable_Item',
            },
        ),
    ]
