# Generated by Django 2.1.7 on 2019-04-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_reservableitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasReservableItem',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='business.Business')),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Reservable')),
                ('reservable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.ReservableItem')),
            ],
            options={
                'db_table': 'Has_Reservable_Item',
            },
        ),
    ]
